version: '3.8'

services:

  bache-finder-ml-model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./storage:/storage
    networks:
      - bache-finder-network